version: '3.7'

services:
  selenium:
    # This tag seems to work; some others do not.
    # E.g., :latest tag throws ERR_SSL_PROTOCOL_ERROR.
    # If problems occur, we can explore more tags:
    # https://hub.docker.com/r/selenium/standalone-chrome/
    image: selenium/standalone-chrome:3.141.59-xenon
    ports:
      - 4444:4444
    volumes:
      - /dev/shm:/dev/shm
    environment:
      # https://stackoverflow.com/a/63310469
      - JAVA_OPTS=-Dwebdriver.chrome.whitelistedIps=
      # https://github.com/SeleniumHQ/docker-selenium/issues/429
      - START_XVFB=false
    container_name: selenium

  app:
    volumes:
      - ../spec/fixtures:/data:ro
    environment:
      - RAILS_ENV=test
      - FINDING_AID_DATA=spec/fixtures
    command:
      - bundle
      - exec
      - rake
      - seed:fixtures
      - db:reset
      - spec
    ports:
      - '3002:3002'
    depends_on:
      - selenium

  solr:
    logging:
      driver: none
