version: '3.7'

volumes:
  pg_data:

services:
  solr:
    ports:
      - "8983:8983"
    volumes:
      - ../solr/arclight:/var/solr/data/arclight

  db:
    volumes:
      - pg_data:/var/lib/postgresql/data

  app:
    volumes:
      - ..:/opt/app-root
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
      - FINDING_AID_DATA=../sample-ead

  redis:
    image: redis:6-buster

  resque:
    image: dul-arclight
    depends_on:
      - db
      - redis
      - solr
    volumes:
      - ..:/opt/app-root
    environment:
      - DATABASE_URL=postgresql://postgres:arclight@db/arclight
      - FINDING_AID_DATA=../../finding-aid-data
      - RAILS_ENV=development
      - REDIS_URL=redis://redis:6379
      - SOLR_URL=http://solr:8983/solr/arclight
    healthcheck:
      disable: true
    stop_signal: SIGQUIT
    entrypoint:
      - wait-for-it
      - db:5432
      - '--'
    command:
      - bundle
      - exec
      - rake
      - resque:pool

  resque-web:
    image: dul-arclight
    ports:
      - "8080:8080"
    depends_on:
      - redis
    volumes:
      - ..:/opt/app-root
    environment:
      - DATABASE_URL=postgresql://postgres:arclight@db/arclight
      - RAILS_ENV=development
      - REDIS_URL=redis://redis:6379
      - SOLR_URL=http://solr:8983/solr/arclight
    healthcheck:
      disable: true
    entrypoint:
      - wait-for-it
      - redis:6379
      - '--'
    command:
      - bundle
      - exec
      - resque-web
      - '-p'
      - '8080'
      - '-r'
      - redis:6379
      - '-F'
